import type { Metadata, Viewport } from 'next'

import { SiteHeader } from '@/components/layouts/site-header'
import { ThemeProvider } from '@/components/providers'

import { fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

import { NuqsAdapter } from 'nuqs/adapters/next/app'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Cookie Run Kingdom',
  description: 'Generated by scy',
  icons: {
    icon: '/icon.png',
  },
}

export const viewport: Viewport = {
  colorScheme: 'dark light',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-cn" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <main className="flex-1">{children}</main>
          </div>
        </ThemeProvider>

      </body>
    </html>
  )
}
